

const student = [{
    
    id          : 1,   
    roll        : 2,   
    name        : 'Asraful Haque',   
    age         : 12,   
    location    : 'Mirpur',   
    gender      : 'Male',   
    bn          : 67,   
    en          : 90,   
    math        : 67,   
    s           : 90,   
    ss          : 67,   
    rel         : 45,   
},
{
    id          : 2,   
    roll        : 2,   
    name        : 'Jubayir Rhaman',   
    age         : 19,   
    location    : 'Mirpur',   
    gender      : 'Male',   
    bn          : 45,   
    en          : 40,   
    math        : 57,   
    s           : 50,   
    ss          : 67,   
    rel         : 45,    
},
 {  id          : 3,   
    roll        : 3,   
    name        : 'APu Das',   
    age         : 34,   
    location    : 'Uttara',   
    gender      : 'Male',   
    bn          : 34,   
    en          : 40,   
    math        : 67,   
    s           : 90,   
    ss          : 67,   
    rel         : 45,  
},
{   id          : 4,   
    roll        : 4,   
    name        :'Dipa CH',   
    age         : 27,   
    location    : 'Uttara',   
    gender      : 'Female',   
    bn          : 34,   
    en          : 20,   
    math        : 67,   
    s           : 90,   
    ss          : 67,   
    rel         : 45,  
},
{   id          : 5,   
    roll        : 5,   
    name        : 'Shobita Bhabi',   
    age         : 34,   
    location    : 'Dhaka',   
    gender      : 'Female',   
    bn          : 34,   
    en          : 80,   
    math        : 67,   
    s           : 90,   
    ss          : 30,   
    rel         : 45,  
},
{   id          : 6,   
    roll        : 6,   
    name        : 'Poalsh das',   
    age         : 34,   
    location    : 'Dhaka',   
    gender      : 'Male',   
    bn          : 89,   
    en          : 80,   
    math        : 87,   
    s           : 90,   
    ss          : 90,   
    rel         : 75,  
},
{   id          : 7,   
    roll        : 7,   
    name        : 'Tipu Chodwery',   
    age         : 34,   
    location    : 'Dhaka',   
    gender      : 'Male',   
    bn          : 100,   
    en          : 95,   
    math        : 98,   
    s           : 99,   
    ss          : 99,   
    rel         : 95,  
},
{   id          : 8,   
    roll        : 8,   
    name        : 'Promod shil',   
    age         : 34,   
    location    : 'Uttarra',   
    gender      : 'Male',   
    bn          : 90,   
    en          : 80,   
    math        : 80,   
    s           : 70,   
    ss          : 90,   
    rel         : 95,  
},
{   id          : 9,   
    roll        : 9,   
    name        : 'Nipas da',   
    age         : 45,   
    location    : 'Hobipur',   
    gender      : 'Male',   
    bn          : 89,   
    en          : 80,   
    math        : 97,   
    s           : 90,   
    ss          : 90,   
    rel         : 95,  
},
{   id          : 10,   
    roll        : 10,   
    name        : 'Anik Das',   
    age         : 34,   
    location    : 'Dhaka',   
    gender      : 'Male',   
    bn          : 89,   
    en          : 80,   
    math        : 87,   
    s           : 90,   
    ss          : 45,   
    rel         : 75,  
},
];